# Generated by Django 4.2.28 on 2026-04-06 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRun',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_id', models.CharField(default=projects.models.generate_project_id, editable=False, max_length=20, unique=True)),
                ('pipeline', models.CharField(choices=[('TIMEPOINT', 'Timepoint Selection'), ('SEQUENCE', 'Sequence Analysis')], max_length=20)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('RUNNING', 'Running'), ('FAILED', 'Failed'), ('SUCCESS', 'Success')], default='CREATED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config', models.JSONField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('files', models.ManyToManyField(related_name='projects', to='uploads.file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimepointResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_json', models.JSONField()),
                ('last_run_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('RUNNING', 'Running'), ('FAILED', 'Failed'), ('SUCCESS', 'Success')], default='SUCCESS', max_length=10)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timepoint_result', to='projects.projectrun')),
            ],
        ),
    ]
