# Generated by Django 4.2.28 on 2026-04-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrun',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='timepointresult',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
