# Generated by Django 4.2.28 on 2026-04-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectrun_celery_task_id_alter_timepointresult_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timepointresult',
            name='last_run_at',
        ),
        migrations.RemoveField(
            model_name='timepointresult',
            name='status',
        ),
        migrations.AddField(
            model_name='projectrun',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
