# Generated by Django 4.2.28 on 2026-04-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_timepointresult_last_run_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrun',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('FAILED', 'Failed'), ('SUCCESS', 'Success')], default='CREATED', max_length=10),
        ),
    ]
