[supervisord]
nodaemon=true
user=appuser
pidfile=/app/supervisord.pid
logfile=/app/supervisord.log
logfile_maxbytes=50MB
logfile_backups=2
loglevel=info

[program:web]
command=gunicorn core.wsgi:application --bind 0.0.0.0:10000
directory=/app
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autostart=true
autorestart=true

[program:worker]
command=celery -A core worker --loglevel=info
directory=/app
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autostart=true
autorestart=true