# Generated by Django 4.2.28 on 2026-04-17 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uploads.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('upload_id', models.CharField(db_collation='C', default=uploads.models.generate_upload_id, editable=False, max_length=20, unique=True)),
                ('file', models.FileField(upload_to=uploads.models.upload_file_path)),
                ('original_filename', models.TextField()),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UPLOADING', 'Uploading'), ('UPLOADED', 'Uploaded'), ('FAILED', 'Failed')], default='UPLOADING', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('md5', models.CharField(blank=True, max_length=64, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
