# Generated by Django 4.2.28 on 2026-04-08 11:48

from django.db import migrations, models
import uploads.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='upload_id',
            field=models.CharField(db_collation='C', default=uploads.models.generate_upload_id, editable=False, max_length=20, unique=True),
        ),
    ]
